version: "3.7"
services:
  adguard-home:
    image: adguard/adguardhome
    container_name: adguard-home
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "853:853/tcp"
      - "3000:3000/tcp"
    volumes:
      - "./adguard/work:/opt/adguardhome/work"
      - "./adguard/conf:/opt/adguardhome/conf"
    restart: unless-stopped